import QtQuick 2.12
import QtQuick.Window 2.12

// DO NOT EDIT THIS FILE

Window {
    visible: true
    width: 640
    height: 480
    title: qsTr("Elmstone Technical Challenge")

    Image {
        id: image
        source: "qrc:/elmstone-logo-2400-260.png"
        anchors.fill: parent
        fillMode: Image.PreserveAspectFit
        visible: false
    }

    ShaderItem {
        anchors.centerIn: image
        width: image.paintedWidth
        height: image.paintedHeight
        source: image
    }
}
